/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginTriageRouteImport } from './routes/login.triage'
import { Route as LoginReceptionistRouteImport } from './routes/login.receptionist'
import { Route as LoginPharmacyRouteImport } from './routes/login.pharmacy'
import { Route as LoginLabRouteImport } from './routes/login.lab'
import { Route as LoginClinicianRouteImport } from './routes/login.clinician'
import { Route as DashboardTriageRouteImport } from './routes/dashboard.triage'
import { Route as DashboardReceptionistRouteImport } from './routes/dashboard.receptionist'
import { Route as DashboardPharmacyRouteImport } from './routes/dashboard.pharmacy'
import { Route as DashboardLabRouteImport } from './routes/dashboard.lab'
import { Route as DashboardClinicianRouteImport } from './routes/dashboard.clinician'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginTriageRoute = LoginTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => LoginRoute,
} as any)
const LoginReceptionistRoute = LoginReceptionistRouteImport.update({
  id: '/receptionist',
  path: '/receptionist',
  getParentRoute: () => LoginRoute,
} as any)
const LoginPharmacyRoute = LoginPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => LoginRoute,
} as any)
const LoginLabRoute = LoginLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => LoginRoute,
} as any)
const LoginClinicianRoute = LoginClinicianRouteImport.update({
  id: '/clinician',
  path: '/clinician',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardTriageRoute = DashboardTriageRouteImport.update({
  id: '/dashboard/triage',
  path: '/dashboard/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReceptionistRoute = DashboardReceptionistRouteImport.update({
  id: '/dashboard/receptionist',
  path: '/dashboard/receptionist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPharmacyRoute = DashboardPharmacyRouteImport.update({
  id: '/dashboard/pharmacy',
  path: '/dashboard/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLabRoute = DashboardLabRouteImport.update({
  id: '/dashboard/lab',
  path: '/dashboard/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClinicianRoute = DashboardClinicianRouteImport.update({
  id: '/dashboard/clinician',
  path: '/dashboard/clinician',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/dashboard/clinician': typeof DashboardClinicianRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/receptionist': typeof DashboardReceptionistRoute
  '/dashboard/triage': typeof DashboardTriageRoute
  '/login/clinician': typeof LoginClinicianRoute
  '/login/lab': typeof LoginLabRoute
  '/login/pharmacy': typeof LoginPharmacyRoute
  '/login/receptionist': typeof LoginReceptionistRoute
  '/login/triage': typeof LoginTriageRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/clinician': typeof DashboardClinicianRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/receptionist': typeof DashboardReceptionistRoute
  '/dashboard/triage': typeof DashboardTriageRoute
  '/login/clinician': typeof LoginClinicianRoute
  '/login/lab': typeof LoginLabRoute
  '/login/pharmacy': typeof LoginPharmacyRoute
  '/login/receptionist': typeof LoginReceptionistRoute
  '/login/triage': typeof LoginTriageRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/dashboard/clinician': typeof DashboardClinicianRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/receptionist': typeof DashboardReceptionistRoute
  '/dashboard/triage': typeof DashboardTriageRoute
  '/login/clinician': typeof LoginClinicianRoute
  '/login/lab': typeof LoginLabRoute
  '/login/pharmacy': typeof LoginPharmacyRoute
  '/login/receptionist': typeof LoginReceptionistRoute
  '/login/triage': typeof LoginTriageRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard/clinician'
    | '/dashboard/lab'
    | '/dashboard/pharmacy'
    | '/dashboard/receptionist'
    | '/dashboard/triage'
    | '/login/clinician'
    | '/login/lab'
    | '/login/pharmacy'
    | '/login/receptionist'
    | '/login/triage'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/clinician'
    | '/dashboard/lab'
    | '/dashboard/pharmacy'
    | '/dashboard/receptionist'
    | '/dashboard/triage'
    | '/login/clinician'
    | '/login/lab'
    | '/login/pharmacy'
    | '/login/receptionist'
    | '/login/triage'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dashboard/clinician'
    | '/dashboard/lab'
    | '/dashboard/pharmacy'
    | '/dashboard/receptionist'
    | '/dashboard/triage'
    | '/login/clinician'
    | '/login/lab'
    | '/login/pharmacy'
    | '/login/receptionist'
    | '/login/triage'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRouteWithChildren
  DashboardClinicianRoute: typeof DashboardClinicianRoute
  DashboardLabRoute: typeof DashboardLabRoute
  DashboardPharmacyRoute: typeof DashboardPharmacyRoute
  DashboardReceptionistRoute: typeof DashboardReceptionistRoute
  DashboardTriageRoute: typeof DashboardTriageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/triage': {
      id: '/login/triage'
      path: '/triage'
      fullPath: '/login/triage'
      preLoaderRoute: typeof LoginTriageRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/receptionist': {
      id: '/login/receptionist'
      path: '/receptionist'
      fullPath: '/login/receptionist'
      preLoaderRoute: typeof LoginReceptionistRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/pharmacy': {
      id: '/login/pharmacy'
      path: '/pharmacy'
      fullPath: '/login/pharmacy'
      preLoaderRoute: typeof LoginPharmacyRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/lab': {
      id: '/login/lab'
      path: '/lab'
      fullPath: '/login/lab'
      preLoaderRoute: typeof LoginLabRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/clinician': {
      id: '/login/clinician'
      path: '/clinician'
      fullPath: '/login/clinician'
      preLoaderRoute: typeof LoginClinicianRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/triage': {
      id: '/dashboard/triage'
      path: '/dashboard/triage'
      fullPath: '/dashboard/triage'
      preLoaderRoute: typeof DashboardTriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/receptionist': {
      id: '/dashboard/receptionist'
      path: '/dashboard/receptionist'
      fullPath: '/dashboard/receptionist'
      preLoaderRoute: typeof DashboardReceptionistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/pharmacy': {
      id: '/dashboard/pharmacy'
      path: '/dashboard/pharmacy'
      fullPath: '/dashboard/pharmacy'
      preLoaderRoute: typeof DashboardPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/lab': {
      id: '/dashboard/lab'
      path: '/dashboard/lab'
      fullPath: '/dashboard/lab'
      preLoaderRoute: typeof DashboardLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/clinician': {
      id: '/dashboard/clinician'
      path: '/dashboard/clinician'
      fullPath: '/dashboard/clinician'
      preLoaderRoute: typeof DashboardClinicianRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginClinicianRoute: typeof LoginClinicianRoute
  LoginLabRoute: typeof LoginLabRoute
  LoginPharmacyRoute: typeof LoginPharmacyRoute
  LoginReceptionistRoute: typeof LoginReceptionistRoute
  LoginTriageRoute: typeof LoginTriageRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginClinicianRoute: LoginClinicianRoute,
  LoginLabRoute: LoginLabRoute,
  LoginPharmacyRoute: LoginPharmacyRoute,
  LoginReceptionistRoute: LoginReceptionistRoute,
  LoginTriageRoute: LoginTriageRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRouteWithChildren,
  DashboardClinicianRoute: DashboardClinicianRoute,
  DashboardLabRoute: DashboardLabRoute,
  DashboardPharmacyRoute: DashboardPharmacyRoute,
  DashboardReceptionistRoute: DashboardReceptionistRoute,
  DashboardTriageRoute: DashboardTriageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
